version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003:2003"
      - "2004:2004"
      - "8125:8125/udp"
    volumes:
      - graphite-data:/var/lib/graphite/whisper
      - graphite-conf:/opt/graphite/conf
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - graphite
    restart: unless-stopped

volumes:
  graphite-data:
  graphite-conf:
  grafana-data: